### ISSUE TITLE
What version of SCPToolkit?

### ISSUE THREAD

**Issue by Volkanite** [TheLastRar/SCP2vJoy#1]
What version of SCPToolkit was this designed to work with?

**Comment by TheLastRar** [comment]
ScpToolkit v1.6.238.16010

**Comment by Volkanite** [comment]
Thank you. Awesome program. Can mark as question and close.

**Comment by herberto97** [comment]
hello ..hope this can be viewed again
i'm really facing problems with the latest version of scptoolkit.initially it reads my ps3 controller and installs...but doesn't read my bluetooth dongle...from the second trial,neither the controller nor the dongle are recognised..HELP!
